---
##
# general configuration
##
state-dir: "{{pkg.svc_data_path}}/sensu"

##
# agent configuration
##
agent-host: "{{cfg.agent-host}}"
agent-port: {{cfg.agent-port}}

##
# api configuration
##
api-host: "{{cfg.api-host}}"
api-port: {{cfg.api-port}}

##
# ssl configuration
##
{{#if cfg.cert-file ~}}
cert-file: "{{cfg.cert-file}}"
{{/if ~}}
{{#if cfg.key-file ~}}
key-file: "{{cfg.key-file}}"
{{/if ~}}
{{#if cfg.trusted-ca-file ~}}
trusted-ca-file: "{{cfg.trusted-ca-file}}"
{{/if ~}}
insecure-skip-tls-verify: {{cfg.insecure-skip-tls-verify}}

##
# dashboard configuration
##
dashboard-host: "{{cfg.dashboard-host}}"
dashboard-port: {{cfg.dashboard-port}}

##
# other
##
debug: {{cfg.debug}}
deregistration-handler: "{{cfg.deregistration-handler}}"
log-level: "{{cfg.log-level}}"

##
# etcd config
etcd-listen-client-urls: http://0.0.0.0:{{cfg.etcd_client_port}}
etcd-name: {{sys.ip}}
etcd-initial-cluster: ""
etcd-initial-cluster-state: new
etcd-initial-advertise-peer-urls: http://{{sys.ip}}:{{cfg.etcd_peer_port}}
etcd-listen-peer-urls: http://0.0.0.0:{{cfg.etcd_peer_port}}
